CREATE DATABASE yellowbus;
ALTER DATABASE yellowbus DEFAULT CHARACTER SET utf8;

USE yellowbus;

CREATE TABLE course (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `course_name` VARCHAR(32) NOT NULL UNIQUE,
    PRIMARY KEY (`id`)
)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE route (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `route_name` VARCHAR(32) NOT NULL UNIQUE,
    PRIMARY KEY (`id`)
)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE route_order (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `route_id` INT UNSIGNED NOT NULL,
    `course_id` INT UNSIGNED NOT NULL,
    `order` SMALLINT NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`course_id`) REFERENCES course(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`route_id`) REFERENCES route(`id`) ON DELETE CASCADE
);